### ISSUE TITLE
ques about edge.

### ISSUE THREAD

**Issue by huixiancheng** [sj-li/MINet#1]
Congratulations on being accepted and thanks for the open source work.  
Will the edge part data be considered for open source availability?
https://github.com/sj-li/MINet/blob/a881fec8fe24ad63be1825a605f6fcf05779e7f2/lib/dataset/SemanticKitti.py#L91-L101

**Comment by sj-li** [comment]
Thanks~
It will be uploaded soon

**Comment by sj-li** [comment]
Sorry for the late reply due to my vacation and happy new year!
I upload the edge files.
Please refer to readme file.
